services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  lakefs-db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - lakefs-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lakefs
      POSTGRES_PASSWORD: lakefspassword
      POSTGRES_DB: lakefs_db
    healthcheck: # <--- เพิ่มส่วนนี้เข้ามา
      test: ["CMD-SHELL", "pg_isready -U lakefs -d lakefs_db -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # ให้เวลากับ PostgreSQL ในการเริ่มทำงานก่อนที่จะเริ่มเช็ค health

  lakefs:
    image: treeverse/lakefs:latest
    ports:
      - "8000:8000"
    depends_on:
      minio:
        condition: service_healthy
      lakefs-db:
        condition: service_healthy # ตอนนี้จะทำงานได้ถูกต้องแล้ว
    environment:
      LAKEFS_DATABASE_CONNECTION_STRING: "postgres://lakefs:lakefspassword@lakefs-db:5432/lakefs_db"
      LAKEFS_AUTH_ENCRYPT_SECRET_KEY: "averysecretkeythatisatleast32bytes"
      LAKEFS_BLOCKSTORE_TYPE: "s3"
      LAKEFS_BLOCKSTORE_S3_ENDPOINT: "http://minio:9000"
      LAKEFS_BLOCKSTORE_S3_REGION: "us-east-1"
      LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE: "true"
      LAKEFS_AUTH_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
      LAKEFS_AUTH_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      LAKEFS_GATEWAYS_S3_DOMAIN_NAME: "s3.local.lakefs.io"

volumes:
  minio-data:
  lakefs-db-data:

networks:
  default:
    name: egat_scraping_network