x-global-environment: &global-environment
  env_file:
    - .env

services:
  lakefsdb:
    container_name: lakefs_server
    image: treeverse/lakefs:1.7.0
    ports:
      - "8001:8000"
    environment:
      LAKEFS_INSTALLATION_USER_NAME: "admin"
      LAKEFS_INSTALLATION_ACCESS_KEY_ID: ${ACCESS_KEY}
      LAKEFS_INSTALLATION_SECRET_ACCESS_KEY: ${SECRET_KEY}
      LAKEFS_DATABASE_TYPE: "local"
      LAKEFS_AUTH_ENCRYPT_SECRET_KEY: "a_very_long_and_random_secret_key_for_lakefs_auth"
      LAKEFS_BLOCKSTORE_TYPE: "local"
      LAKEFS_BLOCKSTORE_LOCAL_PATH: "/home/lakefs/storage"
    <<: *global-environment
    networks:
      - prefect_network
    volumes:
      - ./lakefs_data:/home/lakefs/storage

  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - prefect_db_data:/var/lib/postgresql/data
    <<: *global-environment
    networks:
      - prefect_network

  server:
    container_name: prefect_server
    image: prefecthq/prefect:2-latest
    restart: always
    volumes:
      - prefect_server_data:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    environment:
      PREFECT_UI_URL: "http://127.0.0.1:4200"
      PREFECT_API_URL: "http://prefect_server:4200/api"
      PREFECT_SERVER_API_HOST: "0.0.0.0"
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
    ports:
      - "4200:4200"
    depends_on:
      - database
    <<: *global-environment
    networks:
      - prefect_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: prefect_worker_egat
    restart: always
    entrypoint: ["prefect", "worker", "start", "-p", "default-agent-pool", "-q", "default"]
    working_dir: "/opt/prefect/flows"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PREFECT_API_URL: "http://prefect_server:4200/api"
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      LAKEFS_ENDPOINT: ${LAKEFS_ENDPOINT}
      LAKEFS_REPOSITORY: ${LAKEFS_REPOSITORY}
      LAKEFS_BRANCH: ${LAKEFS_BRANCH}
      LAKEFS_PATH_PARQUET: ${LAKEFS_PATH_PARQUET}
    depends_on:
      - server
      - lakefsdb
    <<: *global-environment
    networks:
      - prefect_network

volumes:
  prefect_db_data:
  prefect_server_data:
  lakefs_data:

networks:
  prefect_network:
    driver: bridge